// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDNkLIC5UhfBO_iXGO5w-E1tWruRlJFL8',
    appId: '1:253104988292:web:3c13f31e9f07c2d31362d1',
    messagingSenderId: '253104988292',
    projectId: 'booking-app-skripsi',
    authDomain: 'booking-app-skripsi.firebaseapp.com',
    storageBucket: 'booking-app-skripsi.appspot.com',
    measurementId: 'G-WR4FWEVCGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_zKGLs5MmmsMsbFhad2oQpIzYU4Civm8',
    appId: '1:253104988292:android:ad611a1cee24c6681362d1',
    messagingSenderId: '253104988292',
    projectId: 'booking-app-skripsi',
    storageBucket: 'booking-app-skripsi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGQXfH-5kmHlW4PmSKUk8FaLWrhLPFC0',
    appId: '1:253104988292:ios:03e95059dbe41c711362d1',
    messagingSenderId: '253104988292',
    projectId: 'booking-app-skripsi',
    storageBucket: 'booking-app-skripsi.appspot.com',
    iosBundleId: 'com.example.userFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGQXfH-5kmHlW4PmSKUk8FaLWrhLPFC0',
    appId: '1:253104988292:ios:03e95059dbe41c711362d1',
    messagingSenderId: '253104988292',
    projectId: 'booking-app-skripsi',
    storageBucket: 'booking-app-skripsi.appspot.com',
    iosBundleId: 'com.example.userFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDNkLIC5UhfBO_iXGO5w-E1tWruRlJFL8',
    appId: '1:253104988292:web:2b1cd949a14eba5e1362d1',
    messagingSenderId: '253104988292',
    projectId: 'booking-app-skripsi',
    authDomain: 'booking-app-skripsi.firebaseapp.com',
    storageBucket: 'booking-app-skripsi.appspot.com',
    measurementId: 'G-WTL4DMCS1F',
  );

}